FROM python:2.7-slim-stretch AS compile-image
RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc \
libpq-dev \
libmemcached-dev \
zlib1g-dev

COPY requirements.txt .
RUN pip install --user -r requirements.txt

FROM python:2.7-slim-stretch AS build-image
COPY --from=compile-image /root/.local /root/.local
COPY . .

# Make sure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH

RUN  \
	python manage.py migrate \
&&	python manage.py createsuperuser \
&&	python manage.py loaddata planets.json \
&&	python manage.py loaddata people.json \
&&	python manage.py loaddata species.json \
&&	python manage.py loaddata transport.json \
&&	python manage.py loaddata starships.json \
&&	python manage.py loaddata vehicles.json \
&&	python manage.py loaddata films.json

EXPOSE 8000

CMD 	python manage.py runserver 0.0.0.0:8000

